---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.5

Naming/FileName:
  Exclude:
    - "lib/open_api-loader.rb"

Style/Alias:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
