---
language: ruby
sudo: false
cache: bundler
bundler_args: --without benchmarks tools
script: bundle exec rake
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - ruby-head
  - jruby-9.1.0.0
  - rbx-3
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: jruby-head
      before_install: gem install bundler --no-ri --no-rdoc
